[build]
  functions = "lambda"

[context.production]
  command = 'gulp && eleventy'
  publish = '_site/'
  environment = { AUCTION_LIVE = "true" }

[context.staging]
  command = 'gulp && eleventy build'
  publish = '_site/'
  environment = { AUCTION_LIVE = "true" }
