[build]
  functions = "lambda"

[context.production]
  command = 'gulp && eleventy'
  publish = '_site/'
  environment = { AUCTION_LIVE = "false" }

[context.staging]
  command = 'gulp && eleventy'
  publish = '_site/'
  environment = { AUCTION_LIVE = "false" }
